### ISSUE TITLE
App does not build 

### ISSUE THREAD

**Issue by harsh253** [scorelab/Go-social#104]
## Expected Behavior

The app should install and run successfully on the physical android device on running the following command
`react-native run-android`

## Current Behavior

After following all the setup instructions from the readme file and also configuring the **config.js** file , when I try to run the command `react-native run-android`, I get the a build error
I do have a device connected with USB debugging enabled.

## Failure Logs

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-gesture-handler:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
81 actionable tasks: 3 executed, 78 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: ./gradlew installDebug

Error: Command failed: ./gradlew installDebug
    at checkExecSyncError (child_process.js:603:11)
    at Object.execFileSync (child_process.js:621:15)
    at runOnAllDevices (/home/harsh/Go-social/node_modules/react-native/local-cli/runAndroid/runAndroid.js:299:19)
    at buildAndRun (/home/harsh/Go-social/node_modules/react-native/local-cli/runAndroid/runAndroid.js:135:12)
    at /home/harsh/Go-social/node_modules/react-native/local-cli/runAndroid/runAndroid.js:65:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by rs4231199** [comment]
@harsh253  I am facing same error. Did you solve it?

**Comment by harsh253** [comment]
Not yet.

**Comment by shehand** [comment]
What is the react native version you've installed @harsh253 @rs4231199 ?

**Comment by rs4231199** [comment]
@shehand 
I am using version 0.58.6 and the command that I ran is **npx react-native run-android**.

**Comment by shehand** [comment]
@rs4231199 Was it the same output for the command **react-native run-android**? (just run the command without **npx**)

**Comment by rs4231199** [comment]
@shehand No change.

**Comment by shehand** [comment]
Refer [this](https://stackoverflow.com/questions/57076748/how-to-fix-react-native-gesture-handlercompiledebugjavawithjavac-failed/57076928)

**Comment by rs4231199** [comment]
`"react-native-gesture-handler": "^1.3.0"` result in a successful build but after that I am getting some new errors 

```
Loading dependency graph, done.
 DELTA  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

::ffff:127.0.0.1 - - [17/Jan/2020:12:34:07 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 200 - "-" "okhttp/3.12.1"
::ffff:127.0.0.1 - - [17/Jan/2020:12:34:08 +0000] "POST /symbolicate HTTP/1.1" 200 - "-" "okhttp/3.12.1"
::ffff:127.0.0.1 - - [17/Jan/2020:12:34:09 +0000] "POST /symbolicate HTTP/1.1" - - "-" "okhttp/3.12.1"
::ffff:127.0.0.1 - - [17/Jan/2020:12:34:14 +0000] "GET /assets/app/images/logo.png?platform=android&hash=62a2dbec1b0bc832a7d908e783f5d6ad HTTP/1.1" - - "-" "okhttp/3.12.1"
::ffff:127.0.0.1 - - [17/Jan/2020:12:34:18 +0000] "POST /symbolicate HTTP/1.1" 200 - "-" "okhttp/3.12.1"
::ffff:127.0.0.1 - - [17/Jan/2020:12:34:21 +0000] "POST /symbolicate HTTP/1.1" 200 - "-" "okhttp/3.12.1"
```

**Comment by shehand** [comment]
@rs4231199 Can you post the screen shots of the errors? It should be on the mobile app if the application was built successfully.

**Comment by rs4231199** [comment]
![Screenshot_2020-01-18-10-56-41-889_com go_social](https://user-images.githubusercontent.com/43215292/72659148-41a55300-39e1-11ea-8f5a-f980ee7d7d3f.jpg)

**Comment by shehand** [comment]
Just shake the phone and make sure to enable the remote debugging and enable hot reloading. That should solve the issue.

**Comment by rs4231199** [comment]
I tried what you suggested but it didn't work. After some googling I found [this](https://github.com/facebook/react-native/issues/20902#issuecomment-431177779) and it worked. As suggested here I made a change in index.js file. Is it okay to do so?

**Comment by harsh253** [comment]
> Refer [this](https://stackoverflow.com/questions/57076748/how-to-fix-react-native-gesture-handlercompiledebugjavawithjavac-failed/57076928)
The 2nd  solution here worked for me. But now I am running into new error

bundling failed: Error: Unable to resolve module `firebase` from `/home/harsh/Go-social/config/config.js`: Module `firebase` does not exist in the Haste module map

**Comment by shehand** [comment]
harsh, can you put the screen shot of the whole error?

**Comment by shehand** [comment]
@harsh253 did you config your config.example.js file and rename it to config.js?

**Comment by shehand** [comment]
Seems like this issue was resolved. I'm closing this issue(inactive issue) as there are no other comments for the past 7 days.
