### ISSUE TITLE
Unable to build the environment

### ISSUE THREAD

**Issue by m1-key** [scorelab/Go-social#105]
![ge1](https://user-images.githubusercontent.com/39923784/73721267-e2b63c80-4749-11ea-9ba5-c6e76fd243c3.JPG)
![ge2](https://user-images.githubusercontent.com/39923784/73721280-e649c380-4749-11ea-9b20-a67fb8a5db01.JPG)
 
Getting this error, tried a lot to fix it using available online solution but still error persists.

**Comment by shehand** [comment]
just put the screenshot after 'what went wrong:'

**Comment by m1-key** [comment]
> just put the screenshot after 'what went wrong:'
![eroor](https://user-images.githubusercontent.com/39923784/74027796-e73f5700-49ce-11ea-94bc-edde4d50f78b.JPG)

**Comment by m1-key** [comment]
@shehand please help to fix this.

**Comment by shehand** [comment]
Have you tried to update the dependencies of the app?

**Comment by m1-key** [comment]
no, it is same as in package.json , i haven't updated any of the dependencies.

**Comment by m1-key** [comment]
@shehand I have question , there are two place where I can run ```react-native run-android```.   
First one is simple I clone the project , and change the directory to Go-social and then run the above command.  
Second is the ```docs``` folder. There is a ```react-native``` folder.  
So which one is the correct one ? I am following the first one.

**Comment by shehand** [comment]
I fix the issue. You can take the PR and run the app or wait until it is merged and try the app after the PR is merged.

**Comment by m1-key** [comment]
@shehand thanks a lot. From where I can get the PR ? And till PR will get merged ?

**Comment by m1-key** [comment]
@shehand Thanks a lot sir , u are awesome . App build was successful. 
But I encountered this : 
![WhatsApp Image 2020-02-08 at 10 45 14](https://user-images.githubusercontent.com/39923784/74079640-57e28400-4a60-11ea-9a4f-3cc84fd7b08a.jpeg)

**Comment by shehand** [comment]
Now those are react native issues. Fix them.

**Comment by m1-key** [comment]
It occurred as soon as build was successful. This was the first screen that popped up after the build. It is not even mentioned which file or function is causing this error.

**Comment by usmailaabdoul** [comment]
Hello pls i encountered this same issue immediately after i successfully installed the app i had it, have u found a solution or wat might have coursed this thanks in advance

**Comment by thomas2308** [comment]
No not yet,  tried everything but still app crashes as soon as build successful

**Comment by usmailaabdoul** [comment]
after having the error i started the remote js debugger this seems to solve the problem but now i am having certain packages which have been moved for my case i had 
createBottomTabNavigation() has been moved to 'react-navigation-tabs'. 
so i had to install this package and aboutt 3 other packages but still haven't succeeded. pls if a mentor could help us address this issue it seems like some of the packages are out dated

**Comment by m1-key** [comment]
one of the package will cause an error, I tried a lot to rectify that but was unable to do so...

**Comment by usmailaabdoul** [comment]
yeah i check one of the packages ( react-navigation) is at version 5 already so when we do npm install some things like createBottomTabNavigation have been upgraded and migrated to different packages or something like that i don't know 
i tried installing a lower version(v4) but still had a lot of complications

**Comment by m1-key** [comment]
@usmailaabdoul have u been able to build the app ? If so , can you help me to build the same ?

**Comment by usmailaabdoul** [comment]
no not really still the same issues

**Comment by usmailaabdoul** [comment]
wat i did was i commented out the part that uses react-navigation and i
render instead  the screen that i want to work on
