### ISSUE TITLE
Not able to connect to remote debugger

### ISSUE THREAD

**Issue by Kanha-13** [scorelab/Go-social#135]
I have build the code successfully, but the app is not connecting with the remote js debugger.
![Screenshot_1647368990](https://user-images.githubusercontent.com/64277596/158616883-644cb1de-0b26-4b64-bc2f-0c648482c65c.png)

I have set the host and port too.

**Comment by Yash621** [comment]
@Kanha-13 can you provide a error log of your console ,so that we can get some clarity in the issue.

**Comment by Kanha-13** [comment]
I have successfully build and there isn't any error. In this image you can see I am getting "Connecting to remote debugger" and the app stuck here only. I have also checked the firewall settings. I have tested with other apps, they are connecting with the remote debugger perfectly. 
And why the app is opening in debugger mode only why not in development mode?

**Comment by Kanha-13** [comment]
I found the solution for this issue 
add below line in application tag in androidmanifest.xml file 
=> android:usesCleartextTraffic="true"
