### ISSUE TITLE
Unable to setup go-social 

### ISSUE THREAD

**Issue by jan-code26** [scorelab/Go-social#136]
<img width="357" alt="Screenshot 2022-03-15 at 8 45 49 PM" src="https://user-images.githubusercontent.com/62233606/158763222-4334afe1-2545-4423-a395-764167a185c9.png">
I'm getting this mistake while running go-social application .I get it is connected with to Facebook login .Would somebody be able to help me in it

**Comment by Yash621** [comment]
@jan-code26 can you show the error log of your console ,the errors are not clear in this ,we will be needing more info

**Comment by jan-code26** [comment]
<img width="1267" alt="Screenshot 2022-03-17 at 5 04 56 PM" src="https://user-images.githubusercontent.com/62233606/159106862-07e447f0-cfca-4eb3-a245-d2939bf0c2a7.png">

**Comment by jan-code26** [comment]
<img width="606" alt="Screenshot 2022-03-18 at 7 22 41 AM" src="https://user-images.githubusercontent.com/62233606/159131400-cb31d3d7-ace5-45a3-b552-4a6cc887d8c4.png">
this is my package.json file is there anything wrong here?

**Comment by Kanha-13** [comment]
I found the fix 
{
  "presets": [
    "@babel/preset-react",
    "@babel/preset-env",
    "@babel/preset-typescript",
    "@babel/preset-flow"
  ],
  "plugins": [
    "@babel/plugin-syntax-class-properties"
  ]
}


Add above lines to .babelrc

**Comment by Maahi10001** [comment]
> <img alt="Screenshot 2022-03-18 at 7 22 41 AM" width="606" src="https://user-images.githubusercontent.com/62233606/159131400-cb31d3d7-ace5-45a3-b552-4a6cc887d8c4.png">
> 
> this is my package.json file is there anything wrong here?


once try updating the react , firebase and react -native versions

//like this
"dependencies": {
        "email-validator": "^2.0.4",
   -->     "firebase": "^7.24.0",
   -->     "react": "16.18.6",
   -->     "react-native": "^0.67.3",
        "react-native-elements": "^1.1.0",
        "react-native-fbsdk": "1.0.0-rc.3",
        "react-native-gesture-handler": "^1.0.12",
        "react-native-google-places-autocomplete": "^1.3.9",
        "react-native-image-crop-picker": "^0.28.0",
        "react-native-image-picker": "^2.0.0",
        "react-native-maps": "^0.26.1",
        "react-native-maps-directions": "^1.6.0",
        "react-native-micro-animated-button": "0.0.28",
        "react-native-vector-icons": "^6.1.0",
        "react-navigation": "^4.0.6"
    }

this worked for me its atleast building the app succesfully.

**Comment by jan-code26** [comment]
> I found the fix { "presets": [ "@babel/preset-react", "@babel/preset-env", "@babel/preset-typescript", "@babel/preset-flow" ], "plugins": [ "@babel/plugin-syntax-class-properties" ] }
> 
> Replace above lines with existing code in .babelrc

It worked! thank you
