### ISSUE TITLE
Issue in Launching the App.

### ISSUE THREAD

**Issue by Maahi10001** [scorelab/Go-social#141]
## Expected Behavior
Perfectly Running App without no pre-log Errors.

## Current Behavior
The App keeps on stopping though it has no error in the process of setup

## Steps to Reproduce
1. Check the versions of react, react-native and firebase in package.json (make sure they are latest)
2. run the app as usual using terminal.
3. you get it...

## Context
I tried to Run it using different android version (10(Q) , 9(Pie) , 8(Oreo)) but getting the same
I tried to Degrade the node versions which resulted in new issue too.

## Failure Logs
![error](https://user-images.githubusercontent.com/80961448/159171443-14543691-a317-419f-be77-89d5f5ab2678.png)

**Comment by Kanha-13** [comment]
I guess it's because you updated rn version, I also faced the same issue when I tried to upgrade the version

**Comment by Maahi10001** [comment]
> I guess it's because you updated rn version, I also faced the same issue when I tried to upgrade the version

did that worked for you then if yes just ping me up what to do in details thank you btw.

**Comment by Yash621** [comment]
@Maahi10001 Try navigating to `android` folder and try  running `./gradlew bundleRelease`. 
If the above command throws `invalid irregular expression error` refer to this issue #134 ,I have already posted a solution for this :)

**Comment by Kanha-13** [comment]
@Maahi10001 I didn't upgrade my rn , instead I did some workaround by modifying the ./babelrc file, as you suggested to upgrade rn in #136  issue, you can see the fix for that bug overthere

**Comment by Maahi10001** [comment]
> @Maahi10001 Try navigating to `android` folder and try running `./gradlew bundleRelease`. If the above command throws `invalid irregular expression error` refer to this issue #134 ,I have already posted a solution for this :)

i have executed the gradlew batch file it was running quite fine with out errors but did not resloved the issue.

**Comment by Yash621** [comment]
have you tried running `./gradlew clean` ?

**Comment by Maahi10001** [comment]
> have you tried running `./gradlew clean` ?

yes i did but the same app stopped working.

**Comment by Yash621** [comment]
okay so basically I have found one more solution for this , firstly downgrade your `react-native` version to `0.58.6` and `react` to `16.6.3` and `react-native-fbsdk` to `0.8.0` after that try running `npx jetify`.
This probably will work :)
