### ISSUE TITLE
Facebook Login Issue

### ISSUE THREAD

**Issue by YaSh8202** [scorelab/Go-social#171]
## Expected Behavior
I expect the Facebook login and image picker features on the Go-social React Native app to function properly.
## Current Behavior
The Facebook login feature is not working as expected. When I click on the 'Sign up with Facebook' button, an error message appears stating "undefined is not a function".
![Codelabz-login2](https://user-images.githubusercontent.com/91831606/224598967-f51aca03-6586-4057-9bdc-a6d5c91b8fa8.gif)

## Failure Information (for bugs)
After investigation, I found out that the issue is caused by the outdated 'react-native-fbsdk' version. Although it has been updated, its methods have not been updated. Specifically, 'LoginManager.logInWithReadPermissions' should be replaced with 'LoginManager.logInWithPermissions'.

Furthermore, I also encountered the same issue with 'react-native-image-picker'. We need to use 'launchImageLibrary' instead of the outdated method.

## Steps to Reproduce
1. Open the Go-social React Native app
2. Click on the 'Sign up with Facebook' button
3. Error message "undefined is not a function" appears

## Context
I am using the Go-social React Native app on an Android device.

## Failure Logs

Please include any relevant log snippets or files here.
```
 [Error: TransformError SyntaxError: D:\Native\Go-social\app\screens\SignupScreen\signupScreen.js: Unexpected token (214:0)

  212 |   };
  213 | }
> 214 |
      | ^]
 ERROR  TypeError: undefined is not a function, js engine: hermes
 ```

**Comment by ajaman190** [comment]
I am currently working on it.

**Comment by YaSh8202** [comment]
I apologize, @ajaman190 , for not realizing that you had already created this issue.
