### ISSUE TITLE
New post screen UI needs improvement

### ISSUE THREAD

**Issue by YaSh8202** [scorelab/Go-social#178]
## Expected Behavior
I expect the new post screen UI to be visually appealing and user-friendly. The buttons text should be easily visible, and there should be visible input fields for body and image picker should open on clicking on add image button
![Screenshot_1679576526](https://user-images.githubusercontent.com/91831606/227212705-98e60c97-8806-484a-88b1-38b1f2ce5b55.jpg)

## Current Behavior
The current UI of the new post screen is not visually appealing and user-friendly. The buttons text is difficult to read, and there is no visible input field for writing the post. Additionally, there is no input field for adding a post title.
![Screenshot_1679234602 (1)](https://user-images.githubusercontent.com/91831606/226224398-972d1761-55de-4b6d-bddf-edc19f80f66a.jpg)

## Failure Information (for bugs)
The "Add Photo" and "Tag People" buttons are not visible on the new post screen. This appears to be a bug caused by the incorrect usage of the `ListItem` component within a `TouchableOpacity`.

Instead of using a Text component within the `TouchableOpacity` to display the button labels, the `ListItem` component is being used incorrectly, causing the buttons to be hidden.

## Steps to Reproduce
1. Go to the home screen and click on 'what's on you mind?' button.
2. Observe that the buttons text is difficult to read.
3. Observe that there is no visible input field for writing the post.
4.  Observe that there is no input field for adding a post title.

## Context
This issue is occurring on the latest version of the platform. I am using app on Pixel 4 in android studio.

## Failure Logs
N/A

**Comment by suyashrastogi7** [comment]
@shehand  Please assign me this issue as a pre-task for GSOC23.

**Comment by YaSh8202** [comment]
Could you please assign me this issue as a pre-task for GSOC23, @shehand ?
