### ISSUE TITLE
Not sensing react native

### ISSUE THREAD

**Issue by AshishA26** [scorelab/Go-social#26]
I installed react native, the newest version. And I installed android SDK, but still, the react native is not sensing.

![gs1](https://user-images.githubusercontent.com/44419439/48236081-aa7d4e00-e38e-11e8-9d43-129b75c9a4e7.PNG)

Also, please fix the requirements file, and detail the readme.md file more so that a user is able to know what he/she is doing.

**Comment by shehand** [comment]
Have you tried git bash?

**Comment by AshishA26** [comment]
Oh, thanks
