### ISSUE TITLE
Missing dependancies

### ISSUE THREAD

**Issue by AshishA26** [scorelab/Go-social#29]
When doing npm install, it is missing a lot of dependancies.

![gs2](https://user-images.githubusercontent.com/44419439/48236667-4b6d0880-e391-11e8-8c01-a9d1f01addf5.PNG)

And when I audit fix them, it still doesn't work.

![gs3](https://user-images.githubusercontent.com/44419439/48236696-76eff300-e391-11e8-9cfb-c84758f33f7d.PNG)

**Comment by AshishA26** [comment]
It says I have to install them myself, but it doesn't say where to get them, it is also not in the readme file.

**Comment by Danushka96** [comment]
#50 Fixed this issue! Thank You!
