### ISSUE TITLE
Don't build

### ISSUE THREAD

**Issue by FelenAmvrosiy** [scorelab/Go-social#34]
Command "react-native run-android" failed

Out of terminal:

Scanning folders for symlinks in /home/live/Go-social/node_modules (17ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have         
set up your Android development environment:                                          
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by shehand** [comment]
You haven't configured environmental variables properly. Use this [link ](https://facebook.github.io/react-native/docs/getting-started) and make sure the environmental variables are set properly.
