### ISSUE TITLE
Issue in Readme.md

### ISSUE THREAD

**Issue by darshvatsa** [scorelab/Go-social#35]
I think if we need a powerful effect on the customers then we should must move toward perfection.
The readme.md file is containing a very minor issue but even its minor it might affect the customer.
The heading - setup the project, is in small letter, so please fix it.
![image](https://user-images.githubusercontent.com/44691030/48528737-50144e00-e8b6-11e8-837e-48f90591a4a5.png)

**Comment by parammittal16** [comment]
@darshvatsa can i do this ?

**Comment by shehand** [comment]
The readme.md file has been updated.
