### ISSUE TITLE
The Readme.md should be Updated

### ISSUE THREAD

**Issue by ns200310** [scorelab/Go-social#37]
I used to Run this project but at last it said that "Build Failed" The main problem was I didn't setup my Android SDK in Environmental variable's. I didnt know that I should setup my Android SDK in Environmental variable's Because the Readme.md File has not said About the Android SDK under prerequisites. 
![issue](https://user-images.githubusercontent.com/33777572/48674052-4ae12880-eb6e-11e8-86d4-c7ce81c4fa4c.PNG)

**Comment by shehand** [comment]
The readme.md file has been updated.
