### ISSUE TITLE
Update .gitignore

### ISSUE THREAD

**Issue by tintinmovie** [scorelab/Go-social#41]
The .gitignore file should be generated with a tool such as www.gitignore.io to provide the most accurate coverage. The current file has been done manually, meaning some files can be missing. 

A possible gitignore for the repo can be found here: [https://www.gitignore.io/api/osx,buck,node,xcode,android,fastlane,intellij,reactnative](https://www.gitignore.io/api/osx,buck,node,xcode,android,fastlane,intellij,reactnative)

**Comment by NaviRocker** [comment]
This Issue must be closed as a PR regarding this Issue is merged.
