### ISSUE TITLE
Update needs for the README

### ISSUE THREAD

**Issue by Danushka96** [scorelab/Go-social#74]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

-  [x] I am running the latest version
-  [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

Guide how to config the firebase database and Authentication process.

**Comment by shehand** [comment]
Do you have any suggestions for the readme file @Danushka96 ?

**Comment by Danushka96** [comment]
yes, Something like a screenshot of database rules and the authentication rule window

**Comment by Danushka96** [comment]
#40
